#!/usr/bin/env bash

REPO="$HOME/save-watch-history"
WATCHLIST="$REPO/watch-history.txt"

display_help() {
  cat <<-FIN
Watch History Saver
Usage:  watchhist [FLAG]

Flag: -h/--help         Show this help message.
      -s/--save         Save current watching streak.
      -u/--update       Update history.  
      -l/--last <name>  Search for last Episode of a series.
      -a/--all  <name>  Show all Episodes watched of a series.
FIN
}

show_last_episode() {
  local last
  last=$(grep -i "$1" "$WATCHLIST" | tail -n 1)
  if [ -z "$last" ]; then
    echo "Sorry you haven't watched anything like that :("
    exit 1
  fi
  echo "Last Episode: $last"
}

show_all() {
  local all
  all=$(grep -i "$1" "$WATCHLIST")
  if [ -z "$all" ]; then
    echo "Sorry you haven't watched anything like that :("
    exit 1
  fi
  echo "Watched Episodes:"
  echo "$all"
}

show_last() {
  echo "Last watched Episode: $(tail -n 1 "$WATCHLIST")"
}

run() {
  cd "$REPO" || echo "Failed to 'cd' into $REPO"
  git --exec-path="$REPO" pull >/dev/null

  while true; do
    local watching
    watching=$(playerctl metadata xesam:title 2>/dev/null) # Get current title
    if [[ -n "$watching" ]]; then
      if ! grep -Fxq "$watching" "$WATCHLIST"; then # Check if not already in the list
        echo "Saved: $watching"
        echo "$watching" >>"$WATCHLIST"
      else
        echo "Already in watchlist: $watching"
      fi
    fi

    git --exec-path="$REPO" add "$WATCHLIST" >/dev/null
    git --exec-path="$REPO" commit -m "added $watching to watchlist" >/dev/null
    git --exec-path="$REPO" push >/dev/null

    sleep 300 # Check every 5 minutes
  done
}

if [ $# -gt 0 ]; then
  case $1 in
  -h | --help)
    display_help
    exit 0
    ;;
  -s | --save)
    run
    ;;
  -l | --last)
    if [ -z "$2" ]; then
      show_last
      exit 0
    fi
    show_last_episode "$2"
    exit 0
    ;;
  -a | --all)
    if [ -z "$2" ]; then
      echo "Please provide a show name." >/dev/stderr
      exit 1
    fi
    show_all "$2"
    exit 0
    ;;
  -u | --update)
    git --exec-path="$REPO" pull >/dev/null
    ;;
  *)
    echo "Do not know this command '$1'" >/dev/stderr
    display_help
    exit 1
    ;;
  esac
else
  display_help
  exit 0
fi
